### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../assets/credentials.json'

### ISSUE THREAD

**Issue by huseyincenik** [Wikkiee/LeadGenPy#1]
When I try to run the code, I get the following error. Could you help me?

python
Kodu kopyala
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from WebScrapper.store import Store
  File "store.py", line 3, in <module>
    from Configs.google_api_config import service
  File "google_api_config.py", line 32, in <module>        
    service = __initialize()
  File "google_api_config.py", line 20, in __initialize    
    flow = InstalledAppFlow.from_client_secrets_file("../assets/credentials.json", SCOPES)
  File "flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '../assets/credentials.json'

**Comment by Wikkiee** [comment]
Hi @huseyincenik,

Thank you for bringing this up. The current version of Leadgenpy is unfortunately broken and is no longer being maintained. We have developed a better and more stable version to address issues like the one you're experiencing.

If you'd like to learn more or need assistance with the new version, feel free to reach out to me at vigneshmayilsamyr@gmail.com.

Best regards,
Vignesh
